In [0]:
import tensorflow 
from scipy.io import arff
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import math

import numpy
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from keras.utils import np_utils
from sklearn import preprocessing
from keras.layers import Dense, Dropout,Activation
from sklearn.model_selection import train_test_split



from math import sin
from math import radians


In [0]:
#data preprocessing-------------------------------------------------------------------------------------


#importing data set
data = arff.loadarff('EEG_Eye_State.arff')
df = pd.DataFrame(data[0])

df.head()
df.shape[0]
"""
model = Sequential()
model.add(LSTM(32, input_shape=(df.index, 13)))
model.add(Dense(1))
"""


##convertion of data type 
df['eyeDetection'] = df['eyeDetection'].astype('int64')

In [0]:

#put into a dataframe
numpy_matrix = df.as_matrix()
#print (numpy_matrix)


#slice array as data and target
data=numpy_matrix[:,:-1]
target=numpy_matrix[:,14]

print (data)
print (target)

[[4329.23 4009.23 4289.23 ... 4280.51 4635.9  4393.85]
 [4324.62 4004.62 4293.85 ... 4279.49 4632.82 4384.1 ]
 [4327.69 4006.67 4295.38 ... 4282.05 4628.72 4389.23]
 ...
 [4277.44 3990.77 4246.67 ... 4257.95 4591.79 4339.49]
 [4284.62 3991.79 4251.28 ... 4267.18 4596.41 4350.77]
 [4287.69 3997.44 4260.   ... 4274.36 4597.95 4350.77]]
[0. 0. 0. ... 1. 1. 1.]


In [0]:
#data set split as train set and test set.

#nrow(data)
smp_size=int((0.8 *len(df)))
data_train=data[smp_size,:]
#target=numpy_matrix[:,14]



In [0]:
#data preparation for Models

# fix random seed for reproducibility
numpy.random.seed(7)



In [0]:
data = df.iloc[:,:-1]
target = df.iloc[:,14:]
x_train,x_test,y_train,y_test = train_test_split(data,target,test_size = 0.2,random_state = 40)
x_train = preprocessing.normalize(x_train)
x_test = preprocessing.normalize(x_test)

x_train = np.array(x_train)
y_train = np.array(y_train)

y_train.shape
x_train.shape

(11984, 14)

In [0]:
x_train

array([[0.26682229, 0.25109883, 0.26523734, ..., 0.26476197, 0.28495472,
        0.26983396],
       [0.26725807, 0.2491204 , 0.26490329, ..., 0.26627148, 0.28514071,
        0.27142655],
       [0.26686956, 0.24874081, 0.26457574, ..., 0.26543623, 0.2858911 ,
        0.27050226],
       ...,
       [0.26761216, 0.24627328, 0.26459148, ..., 0.26564075, 0.28799726,
        0.27219186],
       [0.26441032, 0.25145592, 0.26344802, ..., 0.26457039, 0.284611  ,
        0.26809755],
       [0.26707925, 0.25004566, 0.26430386, ..., 0.26455889, 0.28471866,
        0.27055563]])

In [0]:
N = x_train.shape[0]
n = x_test.shape[0]
L = 10

In [0]:
x_train_seq = []
y_train_seq = []
x_test_seq = []
y_test_seq = []

In [0]:
for k in range(N -L +1):
    x_train_seq.append(x_train[k:k+L])
    y_train_seq.append(y_train[k:k+L])
x_train_seq = np.array(x_train_seq)
y_train_seq = np.array(y_train_seq)

In [0]:
for k in range(n -L +1):
    x_test_seq.append(x_test[k:k+L])
    y_test_seq.append(y_test[k:k+L])
x_test_seq = np.array(x_test_seq)
y_test_seq = np.array(y_test_seq)

ValueError: ignored

In [0]:
y_train_seq

array([[[0],
        [1],
        [0],
        ...,
        [0],
        [1],
        [0]],

       [[1],
        [0],
        [1],
        ...,
        [1],
        [0],
        [1]],

       [[0],
        [1],
        [0],
        ...,
        [0],
        [1],
        [1]],

       ...,

       [[1],
        [1],
        [0],
        ...,
        [1],
        [0],
        [0]],

       [[1],
        [0],
        [0],
        ...,
        [0],
        [0],
        [0]],

       [[0],
        [0],
        [1],
        ...,
        [0],
        [0],
        [1]]])

In [0]:
model = Sequential()

In [0]:
model.add(LSTM(1, return_sequences=True,input_shape=(x_train_seq.shape[1],x_train_seq.shape[2])))
model.add(Dropout(0.2))

model.add(LSTM(32,return_sequences = True))
model.add(Dropout(0.2))

model.add(Dense(1, activation ='softmax'))

In [0]:
model.compile(loss='mean_squared_error',
              optimizer='adam',
              metrics=['accuracy'])

In [0]:
model.output_shape

In [0]:
history = model.fit(x_train_seq, y_train_seq, batch_size=100, epochs=100 )

NameError: ignored